### ISSUE TITLE
npm start color-1 had problem building ./src/index.js

### ISSUE THREAD

**Issue by step2yeung** [mike-works/modern-javascript#186]
**System Information**
  - OS type and version -> OSX 10.14.2
  - Node version -> 10.11.0

**Describe the bug**
There seems to be updates that has happened to babel and webpack, causing build to fail.

**Fixing the bug:**
TLDR: The below 4 steps helped me with fixing the build failures. Not sure if it is the correct changes to be made

1) missing webpack-cli
```
> node_modules/.bin/webpack-dev-server --colors --quiet --env $1


The CLI moved into a separate package: webpack-cli
Please install 'webpack-cli' in addition to webpack itself to use the CLI
-> When using npm: npm i -D webpack-cli
-> When using yarn: yarn add -D webpack-cli
internal/modules/cjs/loader.js:583
    throw err;
    ^

Error: Cannot find module 'webpack-cli/bin/config-yargs'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:581:15)
    at Function.Module._load (internal/modules/cjs/loader.js:507:25)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (/Users/syeung/Documents/Development/training/mj/modern-javascript/node_modules/webpack-dev-server/bin/webpack-dev-server.js:84:1)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
```

2) after adding webpack-cli, we get webpack error:
which according to: https://github.com/webpack-contrib/extract-text-webpack-plugin#usage
`Since webpack v4 the extract-text-webpack-plugin should not be used for css. Use mini-css-extract-plugin instead.`
```
> node_modules/.bin/webpack-dev-server --colors --quiet --env $1


(node:53919) DeprecationWarning: Tapable.plugin is deprecated. Use new API on `.hooks` instead
/Users/syeung/Documents/Development/training/mj/modern-javascript/node_modules/webpack/lib/Chunk.js:849
		throw new Error(
		^

Error: Chunk.entrypoints: Use Chunks.groupsIterable and filter by instanceof Entrypoint instead
    at Chunk.get (/Users/syeung/Documents/Development/training/mj/modern-javascript/node_modules/webpack/lib/Chunk.js:849:9)
    at /Users/syeung/Documents/Development/training/mj/modern-javascript/node_modules/extract-text-webpack-plugin/dist/index.js:176:48
    at Array.forEach (<anonymous>)
    at /Users/syeung/Documents/Development/training/mj/modern-javascript/node_modules/extract-text-webpack-plugin/dist/index.js:171:18
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/Users/syeung/Documents/Development/training/mj/modern-javascript/node_modules/tapable/lib/HookCodeFactory.js:32:10), <anonymous>:7:1)
    at AsyncSeriesHook.lazyCompileHook (/Users/syeung/Documents/Development/training/mj/modern-javascript/node_modules/tapable/lib/Hook.js:154:20)
    at Compilation.seal (/Users/syeung/Documents/Development/training/mj/modern-javascript/node_modules/webpack/lib/Compilation.js:1242:27)
    at hooks.make.callAsync.err (/Users/syeung/Documents/Development/training/mj/modern-javascript/node_modules/webpack/lib/Compiler.js:546:17)
    at _err0 (eval at create (/Users/syeung/Documents/Development/training/mj/modern-javascript/node_modules/tapable/lib/HookCodeFactory.js:32:10), <anonymous>:11:1)
    at _addModuleChain (/Users/syeung/Documents/Development/training/mj/modern-javascript/node_modules/webpack/lib/Compilation.js:1093:12)
    at processModuleDependencies.err (/Users/syeung/Documents/Development/training/mj/modern-javascript/node_modules/webpack/lib/Compilation.js:1005:9)
    at process._tickCallback (internal/process/next_tick.js:61:11)
```

3) After adding `mini-css-extract-plugin` and modifying `module.js` and `plugin.js` to use `MiniCssExtracterPlugin` instead of `ExtractTextPlugin`
I now get:
```
> node_modules/.bin/webpack-dev-server --colors --env $1


ℹ ｢wds｣: Project is running at http://localhost:3000/
ℹ ｢wds｣: webpack output is served from /assets/
ℹ ｢wds｣: Content not from webpack is served from /Users/syeung/Documents/Development/training/modern-javascript/exercises/color-1
✖ ｢wdm｣: Hash: 4be158e1e9b87eaf19fc
Version: webpack 4.28.3
Time: 4822ms
Built at: 2019-01-01 11:16:15
 4 assets
Entrypoint main = main.css main.js main.css.map main.js.map
 [2] multi (webpack)-dev-server/client?http://localhost:3000 ../../public/styles/app.scss ./src/index.js ./styles/app.scss 64 bytes {0} [built]
 [3] (webpack)-dev-server/client?http://localhost:3000 7.78 KiB {0} [built]
 [4] /Users/syeung/Documents/Development/training/modern-javascript/node_modules/url/url.js 22.8 KiB {0} [built]
 [5] /Users/syeung/Documents/Development/training/modern-javascript/node_modules/punycode/punycode.js 14.3 KiB {0} [built]
 [7] /Users/syeung/Documents/Development/training/modern-javascript/node_modules/url/util.js 314 bytes {0} [built]
 [8] /Users/syeung/Documents/Development/training/modern-javascript/node_modules/querystring-es3/index.js 127 bytes {0} [built]
[11] /Users/syeung/Documents/Development/training/modern-javascript/node_modules/strip-ansi/index.js 161 bytes {0} [built]
[13] /Users/syeung/Documents/Development/training/modern-javascript/node_modules/loglevel/lib/loglevel.js 7.68 KiB {0} [built]
[14] (webpack)-dev-server/client/socket.js 1.05 KiB {0} [built]
[16] (webpack)-dev-server/client/overlay.js 3.58 KiB {0} [built]
[21] (webpack)/hot sync nonrecursive ^\.\/log$ 170 bytes {0} [built]
[23] (webpack)/hot/emitter.js 75 bytes {0} [built]
[25] /Users/syeung/Documents/Development/training/modern-javascript/public/styles/app.scss 39 bytes {0} [built]
[26] ./src/index.js 2.36 KiB {0} [built] [failed] [1 error]
[27] ./styles/app.scss 39 bytes {0} [built]
    + 15 hidden modules

WARNING in configuration
The 'mode' option has not been set, webpack will fallback to 'production' for this value. Set 'mode' option to 'development' or 'production' to enable defaults for each environment.
You can also set it to 'none' to disable any default behavior. Learn more: https://webpack.js.org/concepts/mode/

ERROR in ./src/index.js
Module build failed (from /Users/syeung/Documents/Development/training/modern-javascript/node_modules/babel-loader/lib/index.js):
Error: Plugin/Preset files are not allowed to export objects, only functions. In /Users/syeung/Documents/Development/training/modern-javascript/node_modules/babel-preset-react/lib/index.js
    at createDescriptor (/Users/syeung/Documents/Development/training/modern-javascript/node_modules/@babel/core/lib/config/config-descriptors.js:178:11)
    at items.map (/Users/syeung/Documents/Development/training/modern-javascript/node_modules/@babel/core/lib/config/config-descriptors.js:109:50)
    at Array.map (<anonymous>)
    at createDescriptors (/Users/syeung/Documents/Development/training/modern-javascript/node_modules/@babel/core/lib/config/config-descriptors.js:109:29)
    at createPresetDescriptors (/Users/syeung/Documents/Development/training/modern-javascript/node_modules/@babel/core/lib/config/config-descriptors.js:101:10)
    at presets (/Users/syeung/Documents/Development/training/modern-javascript/node_modules/@babel/core/lib/config/config-descriptors.js:47:19)
    at mergeChainOpts (/Users/syeung/Documents/Development/training/modern-javascript/node_modules/@babel/core/lib/config/config-chain.js:320:26)
    at /Users/syeung/Documents/Development/training/modern-javascript/node_modules/@babel/core/lib/config/config-chain.js:283:7
    at buildRootChain (/Users/syeung/Documents/Development/training/modern-javascript/node_modules/@babel/core/lib/config/config-chain.js:120:22)
    at loadPrivatePartialConfig (/Users/syeung/Documents/Development/training/modern-javascript/node_modules/@babel/core/lib/config/partial.js:85:55)
    at Object.loadPartialConfig (/Users/syeung/Documents/Development/training/modern-javascript/node_modules/@babel/core/lib/config/partial.js:110:18)
    at Object.<anonymous> (/Users/syeung/Documents/Development/training/modern-javascript/node_modules/babel-loader/lib/index.js:140:26)
    at Generator.next (<anonymous>)
    at asyncGeneratorStep (/Users/syeung/Documents/Development/training/modern-javascript/node_modules/babel-loader/lib/index.js:3:103)
    at _next (/Users/syeung/Documents/Development/training/modern-javascript/node_modules/babel-loader/lib/index.js:5:194)
    at /Users/syeung/Documents/Development/training/modern-javascript/node_modules/babel-loader/lib/index.js:5:364
 @ multi (webpack)-dev-server/client?http://localhost:3000 ../../public/styles/app.scss ./src/index.js ./styles/app.scss main[2]
Child mini-css-extract-plugin ../../node_modules/css-loader/index.js!../../node_modules/sass-loader/lib/loader.js!styles/app.scss:
    Entrypoint mini-css-extract-plugin = *
    [0] /Users/syeung/Documents/Development/training/modern-javascript/node_modules/css-loader!/Users/syeung/Documents/Development/training/modern-javascript/node_modules/sass-loader/lib/loader.js!./styles/app.scss 165 bytes {0} [built]
    [1] /Users/syeung/Documents/Development/training/modern-javascript/node_modules/css-loader/lib/css-base.js 2.21 KiB {0} [built]
Child mini-css-extract-plugin ../../node_modules/css-loader/index.js!../../node_modules/sass-loader/lib/loader.js!../../public/styles/app.scss:
    Entrypoint mini-css-extract-plugin = *
    [0] /Users/syeung/Documents/Development/training/modern-javascript/node_modules/css-loader!/Users/syeung/Documents/Development/training/modern-javascript/node_modules/sass-loader/lib/loader.js!/Users/syeung/Documents/Development/training/modern-javascript/public/styles/app.scss 354 bytes {0} [built]
    [1] /Users/syeung/Documents/Development/training/modern-javascript/node_modules/css-loader/lib/css-base.js 2.21 KiB {0} [built]
ℹ ｢wdm｣: Failed to compile.
```
I found this is due `babel-preset-react` moving to `@babel/preset-react`: https://github.com/babel/babel/issues/6808#issuecomment-343792786

This seems to hold true for a few other dependencies:
```
     babel-core => @babel/core
     babel-preset-env => @babel/preset-env
     babel-preset-stage-2 =>@babel/preset-stage-2
```

So yarn adding the dependencies above and updating `.babelrc` to:
```
{
  "presets": [
    "@babel/preset-react",
    [
      "@babel/preset-env",
      {
        "targets": {
          "browsers": [
            "last 2 versions",
            "safari >= 7"
          ]
        }
      }
    ],
    "@babel/preset-stage-2"
  ]
}
```

4) After the changes in 3), I get one more error, which was due to preset-stages being deprecated: https://babeljs.io/docs/en/babel-preset-stage-2
The fix for that was to remove `"@babel/preset-stage-2"` from `.babelrc`

The error:
```
> node_modules/.bin/webpack-dev-server --colors --env $1


ℹ ｢wds｣: Project is running at http://localhost:3000/
ℹ ｢wds｣: webpack output is served from /assets/
ℹ ｢wds｣: Content not from webpack is served from /Users/syeung/Documents/Development/training/modern-javascript/exercises/color-1
✖ ｢wdm｣: Hash: 309c80e50b4307867152
Version: webpack 4.28.3
Time: 5142ms
Built at: 2019-01-01 11:45:05
 4 assets
Entrypoint main = main.css main.js main.css.map main.js.map
 [2] multi (webpack)-dev-server/client?http://localhost:3000 ../../public/styles/app.scss ./src/index.js ./styles/app.scss 64 bytes {0} [built]
 [3] (webpack)-dev-server/client?http://localhost:3000 7.78 KiB {0} [built]
 [4] /Users/syeung/Documents/Development/training/modern-javascript/node_modules/url/url.js 22.8 KiB {0} [built]
 [5] /Users/syeung/Documents/Development/training/modern-javascript/node_modules/punycode/punycode.js 14.3 KiB {0} [built]
 [7] /Users/syeung/Documents/Development/training/modern-javascript/node_modules/url/util.js 314 bytes {0} [built]
 [8] /Users/syeung/Documents/Development/training/modern-javascript/node_modules/querystring-es3/index.js 127 bytes {0} [built]
[11] /Users/syeung/Documents/Development/training/modern-javascript/node_modules/strip-ansi/index.js 161 bytes {0} [built]
[13] /Users/syeung/Documents/Development/training/modern-javascript/node_modules/loglevel/lib/loglevel.js 7.68 KiB {0} [built]
[14] (webpack)-dev-server/client/socket.js 1.05 KiB {0} [built]
[16] (webpack)-dev-server/client/overlay.js 3.58 KiB {0} [built]
[21] (webpack)/hot sync nonrecursive ^\.\/log$ 170 bytes {0} [built]
[23] (webpack)/hot/emitter.js 75 bytes {0} [built]
[25] /Users/syeung/Documents/Development/training/modern-javascript/public/styles/app.scss 39 bytes {0} [built]
[26] ./src/index.js 3.2 KiB {0} [built] [failed] [1 error]
[27] ./styles/app.scss 39 bytes {0} [built]
    + 15 hidden modules

WARNING in configuration
The 'mode' option has not been set, webpack will fallback to 'production' for this value. Set 'mode' option to 'development' or 'production' to enable defaults for each environment.
You can also set it to 'none' to disable any default behavior. Learn more: https://webpack.js.org/concepts/mode/

ERROR in ./src/index.js
Module build failed (from /Users/syeung/Documents/Development/training/modern-javascript/node_modules/babel-loader/lib/index.js):
Error: [BABEL] /Users/syeung/Documents/Development/training/modern-javascript/exercises/color-1/src/index.js:
As of v7.0.0-beta.55, we've removed Babel's Stage presets.
Please consider reading our blog post on this decision at
https://babeljs.io/blog/2018/07/27/removing-babels-stage-presets
for more details. TL;DR is that it's more beneficial in the
  long run to explicitly add which proposals to use.

For a more automatic migration, we have updated babel-upgrade,
https://github.com/babel/babel-upgrade to do this for you with
"npx babel-upgrade".

If you want the same configuration as before:

{
  "plugins": [
    // Stage 2
    ["@babel/plugin-proposal-decorators", { "legacy": true }],
    "@babel/plugin-proposal-function-sent",
    "@babel/plugin-proposal-export-namespace-from",
    "@babel/plugin-proposal-numeric-separator",
    "@babel/plugin-proposal-throw-expressions",

    // Stage 3
    "@babel/plugin-syntax-dynamic-import",
    "@babel/plugin-syntax-import-meta",
    ["@babel/plugin-proposal-class-properties", { "loose": false }],
    "@babel/plugin-proposal-json-strings"
  ]
}

If you're using the same configuration across many separate projects,
keep in mind that you can also create your own custom presets with
whichever plugins and presets you're looking to use.

module.exports = function() {
  return {
    plugins: [
      require("@babel/plugin-syntax-dynamic-import"),
      [require("@babel/plugin-proposal-decorators"), { "legacy": true }],
      [require("@babel/plugin-proposal-class-properties"), { "loose": false }],
    ],
    presets: [
      // ...
    ],
  };
};
 (While processing: "/Users/syeung/Documents/Development/training/modern-javascript/node_modules/@babel/preset-stage-2/lib/index.js")
    at _default (/Users/syeung/Documents/Development/training/modern-javascript/node_modules/@babel/preset-stage-2/lib/index.js:9:9)
    at loadDescriptor (/Users/syeung/Documents/Development/training/modern-javascript/node_modules/@babel/core/lib/config/full.js:165:14)
    at cachedFunction (/Users/syeung/Documents/Development/training/modern-javascript/node_modules/@babel/core/lib/config/caching.js:33:19)
    at loadPresetDescriptor (/Users/syeung/Documents/Development/training/modern-javascript/node_modules/@babel/core/lib/config/full.js:235:63)
    at config.presets.reduce (/Users/syeung/Documents/Development/training/modern-javascript/node_modules/@babel/core/lib/config/full.js:77:21)
    at Array.reduce (<anonymous>)
    at recurseDescriptors (/Users/syeung/Documents/Development/training/modern-javascript/node_modules/@babel/core/lib/config/full.js:74:38)
    at loadFullConfig (/Users/syeung/Documents/Development/training/modern-javascript/node_modules/@babel/core/lib/config/full.js:108:6)
    at process.nextTick (/Users/syeung/Documents/Development/training/modern-javascript/node_modules/@babel/core/lib/transform.js:28:33)
    at _combinedTickCallback (internal/process/next_tick.js:131:7)
    at process._tickCallback (internal/process/next_tick.js:180:9)
 @ multi (webpack)-dev-server/client?http://localhost:3000 ../../public/styles/app.scss ./src/index.js ./styles/app.scss main[2]
Child mini-css-extract-plugin ../../node_modules/css-loader/index.js!../../node_modules/sass-loader/lib/loader.js!styles/app.scss:
    Entrypoint mini-css-extract-plugin = *
    [0] /Users/syeung/Documents/Development/training/modern-javascript/node_modules/css-loader!/Users/syeung/Documents/Development/training/modern-javascript/node_modules/sass-loader/lib/loader.js!./styles/app.scss 165 bytes {0} [built]
    [1] /Users/syeung/Documents/Development/training/modern-javascript/node_modules/css-loader/lib/css-base.js 2.21 KiB {0} [built]
Child mini-css-extract-plugin ../../node_modules/css-loader/index.js!../../node_modules/sass-loader/lib/loader.js!../../public/styles/app.scss:
    Entrypoint mini-css-extract-plugin = *
    [0] /Users/syeung/Documents/Development/training/modern-javascript/node_modules/css-loader!/Users/syeung/Documents/Development/training/modern-javascript/node_modules/sass-loader/lib/loader.js!/Users/syeung/Documents/Development/training/modern-javascript/public/styles/app.scss 354 bytes {0} [built]
    [1] /Users/syeung/Documents/Development/training/modern-javascript/node_modules/css-loader/lib/css-base.js 2.21 KiB {0} [built]
ℹ ｢wdm｣: Failed to compile.
```

**Expected behavior**
Build the app without failure

**Comment by step2yeung** [comment]
Bonus:

`npm test color-1` also fails and requires the following:
```
yarn add babel-core@7.0.0-bridge.0
yarn add babel-jest@23.6.0
```

Before, i get the same error as: https://github.com/facebook/jest/issues/6913
```
 Requires Babel "^7.0.0-0", but was loaded with "6.26.3". If you are sure you have a compatible version of @babel/core, it is likely that something in your build process is loading the wrong version. Inspect the stack trace of this error to look for the first entry that doesn't mention "@babel/core" or "babel-core" to see what is calling Babel.

      at throwVersionError (node_modules/@babel/plugin-proposal-class-properties/node_modules/@babel/helper-plugin-utils/lib/index.js:65:11)
      at Object.assertVersion (node_modules/@babel/plugin-proposal-class-properties/node_modules/@babel/helper-plugin-utils/lib/index.js:13:11)
      at _default (node_modules/@babel/plugin-proposal-class-properties/lib/index.js:81:7)
      at node_modules/@babel/plugin-proposal-class-properties/node_modules/@babel/helper-plugin-utils/lib/index.js:19:12
          at Array.map (<anonymous>)
```

and this comment lists out the needed dependencies to make jest work with babel7:
https://github.com/facebook/jest/issues/6913#issuecomment-422368093
